# SPDX-License-Identifier: GPL-2.0
ifeq ($(CONFIG_SOC_S5E8835),y)
# A546E
dtbo-y += \
	a54x/a54x_sea_open_w00_r00.dtbo \
	a54x/a54x_sea_open_w00_r02.dtbo \
	a54x/a54x_sea_open_w00_r03.dtbo \
	a54x/a54x_sea_open_w00_r05.dtbo

# A546B
dtbo-y += \
	a54x/a54x_eur_open_w00_r00.dtbo \
	a54x/a54x_eur_open_w00_r01.dtbo \
	a54x/a54x_eur_open_w00_r02.dtbo \
	a54x/a54x_eur_open_w00_r03.dtbo \
	a54x/a54x_eur_open_w00_r05.dtbo \
	a54x/a54x_eur_open_w00_r10.dtbo
endif
