# SPDX-License-Identifier: GPL-2.0
ifeq ($(CONFIG_SOC_S5E8835),y)
dtbo-y += \
	a54x/a54x_sea_open_w00_r00.dtbo \
	a54x/a54x_sea_open_w00_r02.dtbo \
	a54x/a54x_sea_open_w00_r03.dtbo \
	a54x/a54x_sea_open_w00_r05.dtbo
endif
