# SPDX-License-Identifier: GPL-2.0
ifeq ($(CONFIG_SOC_S5E8835),y)
# A5460 CN/HK/TW
dtbo-y += \
	a54x/a54x_chn_hk_w00_00.dtbo \
	a54x/a54x_chn_hk_w00_02.dtbo \
	a54x/a54x_chn_hk_w00_03.dtbo \
	a54x/a54x_chn_hk_w00_05.dtbo

# A546B - EU
dtbo-y += \
	a54x/a54x_eur_open_w00_r00.dtbo \
	a54x/a54x_eur_open_w00_r01.dtbo \
	a54x/a54x_eur_open_w00_r02.dtbo \
	a54x/a54x_eur_open_w00_r03.dtbo \
	a54x/a54x_eur_open_w00_r05.dtbo \
	a54x/a54x_eur_open_w00_r10.dtbo

# A546E - SEA
dtbo-y += \
	a54x/a54x_sea_open_w00_r00.dtbo \
	a54x/a54x_sea_open_w00_r02.dtbo \
	a54x/a54x_sea_open_w00_r03.dtbo \
	a54x/a54x_sea_open_w00_r05.dtbo

# A546S - KOR
dtbo-y += \
	a54x/a54x_kor_skt_w00_r00.dtbo \
	a54x/a54x_kor_skt_w00_r02.dtbo \
	a54x/a54x_kor_skt_w00_r03.dtbo \
	a54x/a54x_kor_skt_w00_r05.dtbo

# A546U A546U1 A546V S546V - US/LATAM
dtbo-y += \
	a54x/a54x_usa_open_w00_00.dtbo \
	a54x/a54x_usa_open_w00_02.dtbo \
	a54x/a54x_usa_open_w00_03.dtbo \
	a54x/a54x_usa_open_w00_05.dtbo \
	a54x/a54x_usa_singlew_w00_00.dtbo \
	a54x/a54x_usa_singlew_w00_02.dtbo \
	a54x/a54x_usa_singlew_w00_03.dtbo \
	a54x/a54x_usa_singlew_w00_05.dtbo \
	a54x/a54x_usa_singlex_w00_00.dtbo \
	a54x/a54x_usa_singlex_w00_02.dtbo \
	a54x/a54x_usa_singlex_w00_03.dtbo \
	a54x/a54x_usa_singlex_w00_05.dtbo \
	a54x/a54x_usa_tfn_w00_00.dtbo \
	a54x/a54x_usa_tfn_w00_02.dtbo \
	a54x/a54x_usa_tfn_w00_03.dtbo \
	a54x/a54x_usa_tfn_w00_05.dtbo

# A546W - CAN
dtbo-y += \
	a54x/a54x_can_single_w00_00.dtbo \
	a54x/a54x_can_single_w00_02.dtbo \
	a54x/a54x_can_single_w00_03.dtbo \
	a54x/a54x_can_single_w00_05.dtbo

# SCG21 SC53D - JPN
dtbo-y += \
	a54x/a54x_jpn_dcm_w00_00.dtbo \
	a54x/a54x_jpn_dcm_w00_04.dtbo \
	a54x/a54x_jpn_dcm_w00_05.dtbo \
	a54x/a54x_jpn_kdi_w00_00.dtbo \
	a54x/a54x_jpn_kdi_w00_04.dtbo \
	a54x/a54x_jpn_kdi_w00_05.dtbo
endif
