# SPDX-License-Identifier: GPL-2.0
ifeq ($(CONFIG_ARCH_EXYNOS),y)
ifeq ($(CONFIG_SOC_S5E8835),y)
dtb-y += s5e8835.dtb
dtbo-y += board/erd/s5e8835-erd8835.dtbo
else
dtb-y += \
	exynos5433-tm2.dtb	\
	exynos5433-tm2e.dtb	\
	exynos7-espresso.dtb
endif
endif
